[versions]
annotation = "1.8.0"
coreKtx = "1.13.1"
eitherLib = "3.4.0"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
eitherLib = { module = "io.github.2bllw8:either", version.ref = "eitherLib" }

[plugins]

